proxies:
  - name: Los Angeles-Resi
    type: vless
    server: 154.9.254.179
    port: 24092
    uuid: bf4ca661-7b25-4ebc-96f0-e2cec03c809e
    network: tcp
    tls: true
    encryption: none
    udp: false
    servername: www.tesla.com
    client-fingerprint: chrome
    reality-opts:
      public-key: D1ovaFcRsswDryq181RajZ5AmPGobhAkMxUO27uN808
      short-id: "080b527f"
      spider-x: "/"

  - name: Los Angeles-DC
    type: vless
    server: 38.92.15.185
    port: 27788
    uuid: 9cc18bb5-770a-4963-b5c9-c168a32ebd36
    network: tcp
    tls: true
    encryption: none
    udp: false
    servername: www.tesla.com
    client-fingerprint: chrome
    reality-opts:
      public-key: LT5MkMIWYNoAg8j3PginpritGSfE-gGgZi-Xhdy9g3s
      short-id: "65fac6"
      spider-x: "/"

  - name: Hong Kong
    type: hysteria2
    server: 43.199.123.202
    port: 11152
    password: 9aaf0c88-b1ba-42ee-9c3d-a862c4eb0b49
    udp: true
    skip-cert-verify: true
    alpn:
      - h3

  - name: Singapore
    type: hysteria2
    server: 13.228.29.207
    port: 18888
    password: 765c667a-5611-4025-8705-fb818204a686
    udp: true
    skip-cert-verify: true
    alpn:
      - h3

  - name: Malaysia
    type: hysteria2
    server: 31.97.70.10
    port: 18888
    password: 78c615ec-76dd-422a-a843-102e5f86d526
    udp: true
    skip-cert-verify: true
    alpn:
      - h3

  - name: Tokyo
    type: vless
    server: 64.81.112.218
    port: 443
    uuid: d172cd60-40ae-4305-8ba7-482c7f9ff38e
    network: tcp
    tls: true
    encryption: none
    udp: false
    servername: www.tesla.com
    client-fingerprint: chrome
    reality-opts:
      public-key: f-HxJGx2Sb1u2jX40oNvT_xXTHp06BFeKbg2Sh55bFI
      short-id: "6bfaeb4d7e65"
      spider-x: "/"

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - Tokyo
      - Los Angeles-Resi
      - Los Angeles-DC
      - Hong Kong
      - Singapore
      - Malaysia
      - DIRECT

rule-providers:
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400

  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400

rules:
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
